name: build

on:
  push:
    branches: [ develop-v1 ]
  pull_request:
    branches: [ develop-v1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        architecture: x64

    - name: Install requirements
      run: python3 -m pip install -r requirements.txt

    - name: Deploy
      run: python3 -m mkdocs build -d docs

    - uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: docs
