name: CI

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  GITHUB_FEED: https://nuget.pkg.github.com/rasmus-eventflow/
  GITHUB_USER: rasmus

  NUGET_FEED: https://api.nuget.org/v3/index.json

on:
  pull_request:
    branches:
      - develop-v1

  release:
    types:
      - published

jobs:
  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Release NuGet package
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          VERSION="${VERSION//v}"
          dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION -o packages

      - name: Push to GitHub Feed
        run: |
          for f in ./packages/*.nupkg
          do
            curl -vX PUT -u "$GITHUB_USER:${{ secrets.GITHUB_TOKEN }}" -F package=@$f $GITHUB_FEED
          done

  build:
    runs-on: ubuntu-latest
    
    env:
      EVENTFLOW_VERSION: "0.0.${{ github.run_number }}-pullrequest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core v2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.811

      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore 

      - name: Test
        run: dotnet test -c Release --no-build
      
      - name: Pack
        run: dotnet pack -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$EVENTFLOW_VERSION -p:Version=$EVENTFLOW_VERSION -p:AssemblyVersion=$EVENTFLOW_VERSION

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: "./**/EventFlow*${{ env.EVENTFLOW_VERSION}}.*nupkg"

